
package com.xhc.test.javax.xml.wsimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://ws.xml.javax.test.xhc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Echo {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoInt", targetNamespace = "http://ws.xml.javax.test.xhc.com/", className = "com.xhc.test.javax.xml.wsimpl.EchoInt")
    @ResponseWrapper(localName = "echoIntResponse", targetNamespace = "http://ws.xml.javax.test.xhc.com/", className = "com.xhc.test.javax.xml.wsimpl.EchoIntResponse")
    @Action(input = "http://ws.xml.javax.test.xhc.com/Echo/echoIntRequest", output = "http://ws.xml.javax.test.xhc.com/Echo/echoIntResponse")
    public int echoInt(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoString", targetNamespace = "http://ws.xml.javax.test.xhc.com/", className = "com.xhc.test.javax.xml.wsimpl.EchoString")
    @ResponseWrapper(localName = "echoStringResponse", targetNamespace = "http://ws.xml.javax.test.xhc.com/", className = "com.xhc.test.javax.xml.wsimpl.EchoStringResponse")
    @Action(input = "http://ws.xml.javax.test.xhc.com/Echo/echoStringRequest", output = "http://ws.xml.javax.test.xhc.com/Echo/echoStringResponse")
    public String echoString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.xhc.test.javax.xml.wsimpl.MyObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoMyObject", targetNamespace = "http://ws.xml.javax.test.xhc.com/", className = "com.xhc.test.javax.xml.wsimpl.EchoMyObject")
    @ResponseWrapper(localName = "echoMyObjectResponse", targetNamespace = "http://ws.xml.javax.test.xhc.com/", className = "com.xhc.test.javax.xml.wsimpl.EchoMyObjectResponse")
    @Action(input = "http://ws.xml.javax.test.xhc.com/Echo/echoMyObjectRequest", output = "http://ws.xml.javax.test.xhc.com/Echo/echoMyObjectResponse")
    public MyObject echoMyObject(
        @WebParam(name = "arg0", targetNamespace = "")
        MyObject arg0);

}
